#!/usr/bin/env python3
# -*- coding:utf-8 -*-
# ================================================================================================ #
# Project    : Atelier AI: Studio for AI Designers                                                 #
# Version    : 0.1.0                                                                               #
# Python     : 3.10.4                                                                              #
# Filename   : \etl.yml                                                                            #
# ------------------------------------------------------------------------------------------------ #
# Author     : John James                                                                          #
# Email      : john.james.ai.studio@gmail.com                                                      #
# URL        : https://github.com/john-james-ai/atelier-ai                                         #
# ------------------------------------------------------------------------------------------------ #
# Created    : Tuesday August 16th 2022 04:17:54 am                                                #
# Modified   : Tuesday August 16th 2022 05:40:46 am                                                #
# ------------------------------------------------------------------------------------------------ #
# License    : BSD 3-clause "New" or "Revised" License                                             #
# Copyright  : (c) 2022 John James                                                                 #
# ================================================================================================ #
---

name: fp2022_data_etl
steps:
    1:
        name: data_download_api
        module: atelier.workflow.operators
        operator: KaggleDownloader
        params:
            competition: feedback-prize-effectiveness
            destination: dwh/fp2022/external
            filename: feedback-prize-effectiveness.zip
            force: False
    2:
        name: data_extract_zip
        module: atelier.workflow.operators
        operator: ExtractZip
        params:
            source: dwh/fp2022/external/feedback-prize-effectiveness.zip
            destination: dwh/fp2022/raw
            force: False
    3:
        name: load_data_csv
        module: atelier.workflow.operators
        operator: LoadCSV
        params:
            filepath: dwh/fp2022/raw/train.csv
            encoding_errors: 'ignore'
    4:
        name: data_encode_utf-8
        module: atelier.workflow.operators
        operator: Encoder
        params:
            encoding: utf-8
            column: discourse_text
    5:
        name: save_data_parquet
        module: atelier.workflow.operators
        operator: SaveParquet
        params:
            filepath: dwh/fp2022/staged/train.parquet
            force: True
...